### ISSUE TITLE
Error with cleanstring in helpers

### ISSUE THREAD

**Issue by mattiasostmar** [lokal-profil/BatchUploadTools#10]
Seems to be a Py 2 vs 3 compatibility issue:
http://python-future.org/compatible_idioms.html#iterating-through-dict-keys-values-items

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-62-33196bb8ab0c> in <module>()
      1 for index, row in mexiko.iterrows():
----> 2     create_infofiles(row)

<ipython-input-61-eed48b209120> in create_infofiles(row)
      4     infotext = "{{photograph\n"
      5 
----> 6     new_filename = create_new_filename(row)
      7 
      8     lacking_description = False

<ipython-input-60-0b1bc73c2961> in create_new_filename(row)
     65         #fname = construct_new_name_from_dataframe(row, id_str)
     66         description = compose_description(row)
---> 67         checked_fname = helpers.format_filename(description, "SMVK", id_str)
     68         print("fname: {}\nchecked_fname: {}\n".format(fname, checked_fname))
     69         return fname

/home/mos/anaconda3/lib/python3.5/site-packages/batchupload/helpers.py in format_filename(descr, institution, idno, delimiter)
     90     """
     91     delimiter = delimiter or u' - '
---> 92     descr = shortenString(touchup(cleanString(descr), delimiter))
     93     institution = cleanString(institution)
     94     idno = cleanString(idno)

/home/mos/anaconda3/lib/python3.5/site-packages/batchupload/helpers.py in cleanString(text)
    110                 u'e´': u'é',
    111                 u'”': u' ', u'"': u' ', u'“': u' '}
--> 112     for k, v in bad_char.iteritems():
    113         text = text.replace(k, v)
    114 

AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by lokal-profil** [comment]
please try the `py3compat` branch to see if that resolves the issue
