### ISSUE TITLE
Cannot Pip install - requiring an older version of pywikibot?

### ISSUE THREAD

**Issue by mattiasostmar** [lokal-profil/BatchUploadTools#11]
I can't find out how to find a version number corresponding to the way you've set the requirements in the pip install package, I've got pywikibot==2.0rc5.

`!pip install https://github.com/lokal-profil/BatchUploadTools/tarball/0.0.1`

Collecting https://github.com/lokal-profil/BatchUploadTools/tarball/0.0.1
  Downloading https://github.com/lokal-profil/BatchUploadTools/tarball/0.0.1
     / 81kB 313kB/s
Collecting pywikibot==3.0-dev (from BatchUploadTools==0.0.1)
  Could not find a version that satisfies the requirement pywikibot==3.0-dev (from BatchUploadTools==0.0.1) (from versions: 2.0rc1.post1, 2.0rc1.post2, 2.0rc3, 2.0rc4, 2.0rc5)
No matching distribution found for pywikibot==3.0-dev (from BatchUploadTools==0.0.1)
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by lokal-profil** [comment]
You need to add the `--process-dependency-links` flag. I'll mention that in the README.

**Comment by mattiasostmar** [comment]
Not sure if I did it right - pointing to the correct branch:

`!pip install --process-dependency-links https://github.com/lokal-profil/BatchUploadTools/tree/py3compat`

Collecting https://github.com/lokal-profil/BatchUploadTools/tree/py3compat
  Downloading https://github.com/lokal-profil/BatchUploadTools/tree/py3compat
     / 81kB 294kB/s
  Cannot unpack file /private/var/folders/8d/3zhvmhxd7_vg_hhhvwgq9rnm0000gn/T/pip-6nls1spy-unpack/py3compat (downloaded from /private/var/folders/8d/3zhvmhxd7_vg_hhhvwgq9rnm0000gn/T/pip-781cqktn-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /private/var/folders/8d/3zhvmhxd7_vg_hhhvwgq9rnm0000gn/T/pip-781cqktn-build

**Comment by lokal-profil** [comment]
Added instruction in de490e9a88bc4558195933ff090bf7f41d2e9b09

**Comment by mattiasostmar** [comment]
Did work on OS X, but not on ubuntu when I tried:

`08:51 $ !pip install --process-dependency-links git+https://github.com/lokal-profil/BatchUploadTools.git@py3compat`

pip install ipython[notebook] install --process-dependency-links git+https://github.com/lokal-profil/BatchUploadTools.git@py3compat
Collecting git+https://github.com/lokal-profil/BatchUploadTools.git@py3compat
  Cloning https://github.com/lokal-profil/BatchUploadTools.git (to py3compat) to /tmp/pip-ddfu1v21-build
  Requirement already satisfied (use --upgrade to upgrade): BatchUploadTools==0.0.1 from git+https://github.com/lokal-profil/BatchUploadTools.git@py3compat in /home/mos/anaconda3/lib/python3.5/site-packages
  DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.
Requirement already satisfied: ipython[notebook] in /home/mos/anaconda3/lib/python3.5/site-packages
  ipython 5.1.0 does not provide the extra 'notebook'
Collecting install
  Could not find a version that satisfies the requirement install (from versions: )
No matching distribution found for install
✘-1 ~/Dropbox/wmse/batchuploads/BatchUploadTools/batches/Medelhavsmuseet_2016-08 [master|✚ 2019…1253] 

`In [1]: import batchupload.helpers`

ImportError                               Traceback (most recent call last)
<ipython-input-1-a9508d4c42f2> in <module>()
----> 1 import batchupload.helpers

/home/mos/anaconda3/lib/python3.5/site-packages/batchupload/helpers.py in <module>()
      6 import locale  # needed by convertFromCommandline()
      7 import batchupload.common as common
----> 8 from future.utils import iteritems
      9 
     10 # limitations on namelength

ImportError: No module named 'future'

**Comment by lokal-profil** [comment]
Have you already got batchupload  (from local repo)? The `from future.utils import iteritems` is from your pull request, not the py3compat branch
